# config.yaml v1.6
# æ³¨æ„è§„åˆ™åœ¨æ»¡è¶³è‡ªå·±éœ€æ±‚æƒ…å†µä¸‹ï¼Œå°½é‡åšåˆ°ç²¾ç®€ï¼Œä¸è¦è¿‡åº¦å¤æ‚ï¼Œä»¥å…å½±å“æ€§èƒ½ã€‚
# è·‘è£¸æ ¸ç”¨æˆ·è¯·è‡ªè¡Œå»æ‰ä¸‹æ–¹æ§åˆ¶é¢æ¿æ¨¡å—çš„æ³¨é‡Šã€‚
# æœºåœºè®¢é˜…
proxy-providers:
  # ä¸»è¦
  main:
    url: ""
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ç›´è¿

  # æ¬¡è¦
  secondary:
    url: ""
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ç›´è¿

# èŠ‚ç‚¹ä¿¡æ¯
proxies:
  - {name: ç›´è¿, type: direct}

# å…¨å±€é…ç½® 
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
bind-address: "*"
ipv6: false
unified-delay: true
tcp-concurrent: true
# interface-name: enp6s18
log-level: warning
find-process-mode: 'off'
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
profile:
  store-selected: true
  store-fake-ip: true

# ä¸ºé˜²æ­¢ä½¿ç”¨æ’ä»¶æœ‹å‹é‡åˆ°é¢æ¿é—®é¢˜ï¼Œæˆ‘æ³¨é‡Šæ‰äº†æ­¤æ¨¡å—ã€‚
# è·‘è£¸æ ¸æœ‹å‹è‡ªè¡Œåˆ é™¤æ³¨é‡Šå³å¯ï¼Œä½¿ç”¨nikkiä»…å†…æ ¸çš„uiè·¯å¾„æ”¹ä¸º/etc/nikki/run/ui
#external-controller: 0.0.0.0:9090
#secret: ""
#external-ui: "/etc/mihomo/ui"
#external-ui-name: zashboard
#external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"

# å—…æ¢
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: false
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"

# å…¥ç«™  
tun:
  enable: true
  # system/gvisor/mixed
  stack: mixed
  dns-hijack: ["any:53", "tcp://any:53"]
  #ä½¿ç”¨nikkiï¼Œæ··å…¥å…¨éƒ¨ä¸ä¿®æ”¹çš„æƒ…å†µï¼Œå¼€å¯æ¥å£æŒ‡å®šä¸ºnikki
  #ä½¿ç”¨ä»…å†…æ ¸è‡ªè¡Œä¿®æ”¹ä¸‹é¢ä¸‰é¡¹ä¸ºtrue
  #device: nikki
  auto-route: false
  auto-redirect: false
  auto-detect-interface: false

# DNSæ¨¡å—
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  respect-rules: true
  enhanced-mode: redir-host

  default-nameserver:
    - 223.5.5.5
  proxy-server-nameserver:
    - 119.29.29.29
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
 
# å‡ºç«™ç­–ç•¥ï¼Œæ ¹æ®è‡ªå·±æƒ…å†µè°ƒæ•´æ¯ä¸ªç­–ç•¥é‡Œåˆ†ç»„æ’åºï¼Œå¢åˆ éƒ½å¯ä»¥ï¼Œæ¯”å¦‚æŠŠç¾å›½è‡ªåŠ¨æ”¾åˆ°ç¬¬ä¸€ä¸ªï¼Œæ¯”å¦‚åˆ é™¤é¦™æ¸¯æ•…è½¬ï¼Œæ³¨æ„åˆ«æ¼æ‰è¡¨æƒ…é€—å·ç­‰ã€‚
# å¦‚æœç›¸åº”åˆ†ç»„æ²¡æœ‰ç­›é€‰åˆ°å¯¹åº”çš„å›½å®¶ï¼Œè¯·æ ¹æ®è‡ªå·±èŠ‚ç‚¹åå­—è°ƒæ•´ç­›é€‰å…³é”®å­—ã€‚

proxy-group-anchor:
  select_common: &select_common {type: select, proxies: [ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, ğŸ”¯ æ—¥æœ¬æ•…è½¬, ğŸ”¯ é¦™æ¸¯æ•…è½¬, ğŸ”¯ ç¾å›½æ•…è½¬, ğŸ”¯ æ—¥æœ¬æ•…è½¬-secondary, ğŸ”¯ é¦™æ¸¯æ•…è½¬-secondary, ğŸ”¯ ç¾å›½æ•…è½¬-secondary, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨-secondary, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨-secondary, â™»ï¸ ç¾å›½è‡ªåŠ¨-secondary, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, ç›´è¿]}

proxy-groups:
  - {name: ğŸš€ é»˜è®¤ä»£ç†, <<: *select_common}
  - {name: ğŸ“¦ ä¸‹è½½ä¸“ç”¨, type: select, proxies: [ğŸ”¯ æ—¥æœ¬æ•…è½¬-secondary, ğŸ”¯ é¦™æ¸¯æ•…è½¬-secondary, ğŸ”¯ ç¾å›½æ•…è½¬-secondary, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨-secondary, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨-secondary, â™»ï¸ ç¾å›½è‡ªåŠ¨-secondary, â™»ï¸ è‡ªåŠ¨é€‰æ‹©-secondary, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, ç›´è¿]}

# ä¸‹é¢å†™åº”ç”¨æ•´åˆé›†è§„åˆ™ç»„
  - {name: ğŸ“² ç¤¾äº¤è½¯ä»¶, <<: *select_common}

# ä¸‹é¢å†™åº”ç”¨è§„åˆ™ç»„
  - {name: ğŸ¤– ChatGPT, <<: *select_common}
  - {name: ğŸŒ EHentai, <<: *select_common}
  - {name: ğŸ“¹ YouTube, <<: *select_common}
  - {name: ğŸ€ Google, <<: *select_common}
  - {name: ğŸ¥ NETFLIX, <<: *select_common}
  - {name: ğŸ’¶ PayPal, <<: *select_common}


#  - {name: ğŸ‘¨ğŸ¿â€ğŸ’» GitHub, <<: *select_common}
#  - {name: ğŸ¬ OneDrive, <<: *select_common}
#  - {name: ğŸªŸ Microsoft, <<: *select_common}
#  - {name: ğŸµ TikTok, <<: *select_common}
#  - {name: ğŸ“² Telegram, <<: *select_common}

# ä¸è¦åŠ¨!
  - {name: ğŸŸ æ¼ç½‘ä¹‹é±¼, <<: *select_common}

# ä¸‹é¢å†™èŠ‚ç‚¹ç»„
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)æ—¥|jp|japan"}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)æ¸¯|hk|hongkong|hong kong"}
  - {name: ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)ç¾|us|unitedstates|united states"}
  - {name: ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore"}

#  - {name: ğŸ”¯ é¦™æ¸¯æ•…è½¬-main, type: fallback, use: [main], tolerance: 20, interval: 300, filter: "(?=.*(æ¸¯|HK|(?i)Hong))^((?!(å°|æ—¥|éŸ©|æ–°|æ·±|ç¾)).)*$"}
#  - {name: ğŸ”¯ æ—¥æœ¬æ•…è½¬-main, type: fallback, use: [main], tolerance: 20, interval: 300, filter: "(?=.*(æ—¥|JP|(?i)Japan))^((?!(æ¸¯|å°|éŸ©|æ–°|ç¾)).)*$" }
#  - {name: ğŸ”¯ ç¾å›½æ•…è½¬-main, type: fallback, use: [main], tolerance: 20, interval: 300, filter: "(?=.*(ç¾|US|(?i)States|America))^((?!(æ¸¯|å°|éŸ©|æ–°|æ—¥)).)*$"}

  - {name: ğŸ”¯ æ—¥æœ¬æ•…è½¬, type: fallback, include-all: true, tolerance: 2, interval: 15, filter: "(?=.*(æ—¥|JP|(?i)Japan))^((?!(æ¸¯|å°|éŸ©|æ–°|ç¾)).)*$" }
  - {name: ğŸ”¯ é¦™æ¸¯æ•…è½¬, type: fallback, include-all: true, tolerance: 2, interval: 15, filter: "(?=.*(æ¸¯|HK|(?i)Hong))^((?!(å°|æ—¥|éŸ©|æ–°|æ·±|ç¾)).)*$"}
  - {name: ğŸ”¯ ç¾å›½æ•…è½¬, type: fallback, include-all: true, tolerance: 2, interval: 15, filter: "(?=.*(ç¾|US|(?i)States|America))^((?!(æ¸¯|å°|éŸ©|æ–°|æ—¥)).)*$" }

  - {name: ğŸ”¯ æ—¥æœ¬æ•…è½¬-secondary, type: fallback, use: [secondary], tolerance: 2, interval: 15, filter: "(?=.*(æ—¥|JP|(?i)Japan))^((?!(æ¸¯|å°|éŸ©|æ–°|ç¾)).)*$" }
  - {name: ğŸ”¯ é¦™æ¸¯æ•…è½¬-secondary, type: fallback, use: [secondary], tolerance: 2, interval: 15, filter: "(?=.*(æ¸¯|HK|(?i)Hong))^((?!(å°|æ—¥|éŸ©|æ–°|æ·±|ç¾)).)*$"}
  - {name: ğŸ”¯ ç¾å›½æ•…è½¬-secondary, type: fallback, use: [secondary], tolerance: 2, interval: 15, filter: "(?=.*(ç¾|US|(?i)States|America))^((?!(æ¸¯|å°|éŸ©|æ–°|æ—¥)).)*$"}
  
  - {name: â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, type: url-test, use: [main], tolerance: 2, interval: 30, filter: "(?=.*(æ—¥|JP|(?i)Japan))^((?!(æ¸¯|å°|éŸ©|æ–°|ç¾)).)*$" }
  - {name: â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, type: url-test, use: [main], tolerance: 2, interval: 30, filter: "(?=.*(æ¸¯|HK|(?i)Hong))^((?!(å°|æ—¥|éŸ©|æ–°|æ·±|ç¾)).)*$"}
  - {name: â™»ï¸ ç¾å›½è‡ªåŠ¨, type: url-test, use: [main], tolerance: 2, interval: 30, filter: "(?=.*(ç¾|US|(?i)States|America))^((?!(æ¸¯|å°|æ—¥|éŸ©|æ–°)).)*$"}
  - {name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©, type: url-test, use: [main], tolerance: 2, interval: 30, filter: "^((?!(ç›´è¿)).)*$"}

  - {name: â™»ï¸ æ—¥æœ¬è‡ªåŠ¨-secondary, type: url-test, use: [secondary], tolerance: 2, interval: 30, filter: "(?=.*(æ—¥|JP|(?i)Japan))^((?!(æ¸¯|å°|éŸ©|æ–°|ç¾)).)*$" }
  - {name: â™»ï¸ é¦™æ¸¯è‡ªåŠ¨-secondary, type: url-test, use: [secondary], tolerance: 2, interval: 30, filter: "(?=.*(æ¸¯|HK|(?i)Hong))^((?!(å°|æ—¥|éŸ©|æ–°|æ·±|ç¾)).)*$"}
  - {name: â™»ï¸ ç¾å›½è‡ªåŠ¨-secondary, type: url-test, use: [secondary], tolerance: 2, interval: 30, filter: "(?=.*(ç¾|US|(?i)States|America))^((?!(æ¸¯|å°|æ—¥|éŸ©|æ–°)).)*$"}
  - {name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©-secondary, type: url-test, use: [secondary], tolerance: 2, interval: 30, filter: "^((?!(ç›´è¿)).)*$"}

  - {name: ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, type: select, include-all: true}


# è§„åˆ™é›†
## typeï¼šå¯é€‰http/file/inline  behaviorï¼šå¯é€‰domain/ipcidr/classical formatï¼šå¯é€‰yaml/text/mrs
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}

rule-providers: 
  private_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}
  proxylite: { <<: *class, url: "https://raw.githubusercontent.com/qichiyuhub/rule/refs/heads/main/proxy.list"}
  ai: {  <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs" }
  
# åœ¨ä¸‹é¢å†™åº”ç”¨è§„åˆ™é›†
  ehentai_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geosite/ehentai.mrs"}
  steam_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam.mrs" }
  epic_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/epicgames.mrs" }
  youtube_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"}
  google_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"}
  netflix_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"}
  paypal_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs"}
  apple_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs"}
  speedtest_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs"}

#  github_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"}
#  onedrive_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs"}
#  microsoft_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"}
#  tiktok_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs"}
#  telegram_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"}
  
# ä¸‹è½½è§„åˆ™é›†
  game_download: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-game-platforms-download.mrs"}
  android_download: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-android-app-download.mrs"}
  
# æ•´åˆè§„åˆ™é›†
  # é€šä¿¡æœåŠ¡åˆé›† (discord, line, whatsapp...)
  category-communication_domian: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-communication.mrs"}


# ä¸è¦åŠ¨!
  geolocation-!cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}
  cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"}
  
  private_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs"}
  cn_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}
  google_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"}
  netflix_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"}
  apple_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/apple.mrs"}

#  telegram_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"}


# è§„åˆ™åŒ¹é…
rules:
# ç§æœ‰ipå’ŒåŸŸåç›´è¿
  - RULE-SET,private_ip,ç›´è¿,no-resolve
  - RULE-SET,private_domain,ç›´è¿

# ä¸‹é¢å†™è‡ªå®šä¹‰è§„åˆ™
  - DOMAIN-SUFFIX,qichiyu.com,ğŸš€ é»˜è®¤ä»£ç†
  - DOMAIN,proxy.nanodaaa.net,ğŸš€ é»˜è®¤ä»£ç†  # èµ°ä»£ç†
  - DOMAIN-SUFFIX,nanodaaa.net,ç›´è¿  # nanodaaa.net
  
# é»˜è®¤è§„åˆ™
  - RULE-SET,proxylite,ğŸš€ é»˜è®¤ä»£ç†

# ä¸‹è½½è§„åˆ™
  - RULE-SET,game_download,ğŸ“¦ ä¸‹è½½ä¸“ç”¨
  - RULE-SET,android_download,ğŸ“¦ ä¸‹è½½ä¸“ç”¨

# åœ¨ä¸‹é¢å†™åº”ç”¨æ•´åˆè§„åˆ™
  - RULE-SET,category-communication_domian,ğŸ“² ç¤¾äº¤è½¯ä»¶

#  åœ¨è¿™ä¸‹é¢å†™åº”ç”¨åŸŸåè§„åˆ™
  - RULE-SET,ai,ğŸ¤– ChatGPT
  - RULE-SET,youtube_domain,ğŸ“¹ YouTube
  - RULE-SET,ehentai_domain,ğŸŒ EHentai
  - RULE-SET,google_domain,ğŸ€ Google
  - RULE-SET,netflix_domain,ğŸ¥ NETFLIX
  - RULE-SET,paypal_domain,ğŸ’¶ PayPal


  - RULE-SET,apple_domain,ç›´è¿

  
#  - RULE-SET,github_domain,ğŸ‘¨ğŸ¿â€ğŸ’» GitHub
#  - RULE-SET,onedrive_domain,ğŸ¬ OneDrive
#  - RULE-SET,microsoft_domain,ğŸªŸ Microsoft
#  - RULE-SET,tiktok_domain,ğŸµ TikTok
#  - RULE-SET,telegram_domain,ğŸ“² Telegram

#  åœ¨ä¸‹é¢å†™åº”ç”¨ ip è§„åˆ™
  - RULE-SET,apple_ip,ç›´è¿
  - RULE-SET,google_ip,ğŸ€ Google
  - RULE-SET,netflix_ip,ğŸ¥ NETFLIX

#  - RULE-SET,telegram_ip,ğŸ“² Telegram
  

# è¡¥æ¼
  - RULE-SET,geolocation-!cn,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,cn_domain,ç›´è¿
  - RULE-SET,cn_ip,ç›´è¿
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼

